<?php
namespace Ginger\Model\File;

use Ginger\Model\Directory\Inbox;
/**
 * Test class for SourceFile.
 * Generated by PHPUnit on 2013-05-27 at 21:57:50.
 */
class SourceFileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SourceFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Inbox::deleteFiles();
        $this->object = new SourceFile(1, 'sourcefile', '#', 'Ginger.Application');
        $this->object->setOptions(array(
            'file_pattern' => '/^a-test-file\.json$/'
        ));

        file_put_contents('data/inbox/a-test-file.json', json_encode(array(
            'a_key' => 'a value',
            'another_key' => 'another value',
        )));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        Inbox::deleteFiles();
    }

    /**
     * @covers Ginger\Model\File\SourceFile::getData
     */
    public function testGetData()
    {

        $data = $this->object->getData();

        $check = array(
            array(
            'a_key' => 'a value',
            'another_key' => 'another value',
            )
        );

        $this->assertEquals($check, $data);
    }

    /**
     * @covers Ginger\Model\File\SourceFile::getDataStructure
     */
    public function testGetDataStructure()
    {
        $dataStructure = $this->object->getDataStructure();

        $check = array(
            array(
                'name' => 'a_key',
                'type' => 'string'
            ),
            array(
                'name' => 'another_key',
                'type' => 'string'
            )
        );

        $this->assertEquals($check, $dataStructure);
    }

    /**
     * @covers Ginger\Model\File\SourceFile::getDataType
     */
    public function testGetDataType()
    {
        $this->assertEquals(3, $this->object->getDataType());
    }

    /**
     * @covers Ginger\Model\File\SourceFile::getItemCount
     */
    public function testGetItemCountWithObjectData()
    {
        $this->assertEquals(1, $this->object->getItemCount());
    }

    /**
     * @covers Ginger\Model\File\SourceFile::getItemCount
     */
    public function testGetItemCountWithListData()
    {
        file_put_contents('data/inbox/another-file.json', json_encode(array(
            'one', 'two', 'three'
        )));

        $this->object->setOptions(array(
            'file_pattern' => '/^another/'
        ));

        $this->assertEquals(3, $this->object->getItemCount());
    }

    /**
     * @covers Ginger\Model\File\SourceFile::getOptions
     */
    public function testGetOptions()
    {
        $this->assertEquals(
            array('file_pattern' => '/^a-test-file\.json$/'),
            $this->object->getOptions()
        );
    }
}
?>
