<div class="row-fluid">
    <div class="span12">
        <h2><%- headline %></h2>
    </div>
</div>
<% if ($CL.has(obj, 'isFirstUser') && obj.isFirstUser) { %>
<div class="row-fluid">
    <div class="span12">
        <div class="alert alert-block alert-danger"><%- $CL.translate('USERS::HINT::FIRST_USER') %></div>
    </div>
</div>
<% } %>
<div class="row-fluid">
    <div class="span12  row-label-element desktop-span7">
        <% print(Cl.Form.View.InputText.print(form.getElement('lastname'), form.getErrors())); %>
    </div>
    <div class="span0 desktop-span5 visible-desktop"></div>
</div>
<div class="row-fluid">
    <div class="span12  row-label-element desktop-span7">
        <% print(Cl.Form.View.InputText.print(form.getElement('firstname'), form.getErrors())); %>
    </div>
    <div class="span0 desktop-span5 visible-desktop"></div>
</div>
<div class="row-fluid">
    <div class="span12  row-label-element desktop-span7">
        <% print(Cl.Form.View.InputText.print(form.getElement('email'), form.getErrors())); %>
    </div>
    <div class="span0 desktop-span5 visible-desktop"></div>
</div>
<div class="row-fluid">
    <div class="span12  row-label-element desktop-span7">
        <% print(Cl.Form.View.Password.print(form.getElement('password'), form.getErrors())); %>
    </div>
    <div class="span0 desktop-span5 visible-desktop"></div>
</div>
<div class="row-fluid">
    <div class="span12">
        <input type="submit" name="save" value="<%= $CL.translate('FORM::BUTTON::SAVE') %>"
    </div>
</div>