<Doctype html><html>
	<head>
	    <meta charset="UTF-8" />
	    <title>Hinweis zum MS IE < 7.0</title>
	</head>
	<body>
	    <h1>Ihr Browser wird von <?php echo $this->host; ?> nicht unterstuetzt</h1>
	    <p>
		Auf www.codeliner.ws kommen moderne Webtechnologien zum Einsatz.
		Ihr Browser ist seit Jahren ueberholt. Bitte verwenden Sie zum Betrachten von www.codeliner.ws einen aktuellen Browser, der den heutigen Standards entspricht.		
	    </p>
	</body>
</html>