<?php
namespace Ginger\Service\DataStructure;

/**
 * Test class for PlaceholderTool.
 * Generated by PHPUnit on 2013-06-04 at 20:37:12.
 */
class PlaceholderToolTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Ginger\Service\DataStructure\PlaceholderTool::readPlaceholderKeys
     */
    public function testReadPlaceholderKeys()
    {
        $str = 'test_[$DATE]_and_[attribute]_or_[deep::attribute]';

        $check = array(
            '$DATE',
            'attribute',
            'deep::attribute'
        );

        $this->assertEquals($check, PlaceholderTool::readPlaceholderKeys($str));
    }

    /**
     * @covers Ginger\Service\DataStructure\PlaceholderTool::replace
     */
    public function testReplace()
    {
        $str = 'a_[job]_file_with_[id].json';

        $this->assertEquals('a_test_file_with_1.json', PlaceholderTool::replace($str, array('job' => 'test', 'id' => 1)));
    }
}

?>
