<?php
namespace Ginger\Model\Feature;

use Cl\Test\PHPUnitTestCase;
use Ginger\Model\Connector\ConnectorEvent;
use MockObject\TableSource;
/**
 * Test class for FilterFeature.
 * Generated by PHPUnit on 2013-04-26 at 21:54:36.
 */
class FilterFeatureTest extends PHPUnitTestCase
{

    /**
     * @var FilterFeature
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FilterFeature(1, 'StringTrim', '/', 'MockObject');
        $this->object->setServiceLocator($this->getApplication()->getServiceManager());
    }

    /**
     * @covers Ginger\Model\Feature\FilterFeature::getType
     */
    public function testGetType()
    {
        $this->assertEquals('filter', $this->object->getType());
    }

    /**
     * @covers Ginger\Model\Feature\FilterFeature::alterValue
     */
    public function testAlterValue()
    {
        $source = new TableSource(1, 'TableSource', '/', 'MockObject');

        $source->setData(array(
            array('name' => ' with whitespace ')
        ));

        $this->object->setOptions(array(
            'attributes_to_alter' => array(
                'name'
            ),
            'site_to_alter' => 'source'
        ));

        $e = new ConnectorEvent(ConnectorEvent::EVENT_MAP_ITEM);
        $e->setSource($source);
        $e->setItem(array('name' => ' with whitespace '));

        $response = $this->object->onMapItem($e);

        $this->assertNull($response);
        $this->assertEquals('with whitespace', $e->getItem()['name']);
    }



}

?>
