<?php
namespace Ginger\Model\Feature;

use Cl\Test\PHPUnitTestCase;
use Ginger\Model\Connector\ConnectorEvent;
use MockObject\TableSource;
use Ginger\Job\Run\Message;
/**
 * Test class for ValidatorFeature.
 * Generated by PHPUnit on 2013-04-26 at 19:28:51.
 */
class ValidatorFeatureTest extends PHPUnitTestCase
{

    /**
     * @var ValidatorFeature
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ValidatorFeature(1, 'digits', '/digits-validator', 'Ginger.Application');
        $this->object->setServiceLocator($this->getApplication()->getServiceManager());
    }

    /**
     * @covers Ginger\Model\Feature\ValidatorFeature::getType
     */
    public function testGetType()
    {
        $this->assertEquals('validator', $this->object->getType());
    }

    /**
     * @covers Ginger\Model\Feature\ValidatorFeature::alterValue
     */
    public function testAlterValue()
    {
        $source = new TableSource(1, 'TableSource', '/', 'MockObject');

        $source->setData(array(
            array('id' => 1)
        ));

        $this->object->setOptions(array(
            'attributes_to_alter' => array(
                'id'
            ),
            'site_to_alter' => 'source'
        ));

        $e = new ConnectorEvent(ConnectorEvent::EVENT_MAP_ITEM);
        $e->setSource($source);
        $e->setItem(array('id' => 1));

        $response = $this->object->onMapItem($e);

        $this->assertNull($response);

        $source->setData(array(
            array('id' => 'a' )
        ));

        $e->setItem(array('id' => 'a' ));

        $response = $this->object->onMapItem($e);

        $this->assertInstanceOf('Ginger\Job\Run\Message', $response);
        $this->assertEquals(Message::TYPE_ERROR, $response->getType());
        $this->assertEquals("Die Validierung des Attributes \"id\" mit dem Wert \"a\" ist fehlgeschlagen.\nDer Wert darf nur Zahlen enthalten.\n", $response->getText());
    }
}