<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <div class="span12"><a href="#<% print(helpers.uri('jobs_overview')); %>"><h2><%= $CL.translate('HEADLINE::JOBS') %></h2></a></div>
        </div>
        <div class="row-fluid">
            <div id="js_latest_jobruns" class="span12 loading loading-left"></div>
        </div>
    </div>
</div>
<% if ($CL.get('user_manager').getActiveUser().get('isAdmin')) { %>
<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <div class="span12"><h2><%= $CL.translate('HEADLINE::MODULES')%></h2></div>
        </div>
        <div class="row-fluid">
            <div id="js_modules" class="span12"></div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <div class="span12"><a href="#<% print(helpers.uri('users_overview')); %>"><h2><%= $CL.translate('HEADLINE::USERS') %></h2></a></div>
        </div>
    </div>
</div>
<% } %>