<?php echo $this->render('layout/partial/head.phtml'); ?>
    <body>
		<div class="navbar">
		  <div class="navbar-inner">
			<div class="container">
			  <a class="brand" id="logo-mini" href="<?php echo $this->url("home"); ?>">Ginger IMS</a>
			  <div class="nav-collapse">

			  </div><!--/.nav-collapse -->
              <div id="head-nav-right" class="pull-right"></div>
			</div>
		  </div>
		</div>
	<div class="container-fluid">
        <div class="row-fluid">
            <div id="js_breadcrumbs" class="span12"></div>
        </div>
        <div class="row-fluid">
            <div id="js_content" class="span8">
                <?php echo $this->content; ?>
            </div>
            <div class="span4">
                <div id="js-sidebar">

                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12" id="js-footer">
            </div>
        </div>
        <footer>
        </footer>
    </div> <!-- /container -->
	<?php echo $this->render('layout/partial/footer.phtml'); ?>
    </body>
</html>