<?php echo $this->render('layout/partial/head.phtml'); ?>
    <body>
        <div class="row-fluid">
            <div class="span2" style="background-color:yellow">
                span2
            </div>
            <div class="span6" style="background-color:red">
                span6
            </div>
            <div class="span4" style="background-color:blue">
                span4
            </div>
        </div>
        <div class="row-fluid table-style">
            <div class="span12 ts-tr">
                <div class="ts-td2">
                    table row 1
                </div>
                <div class="ts-td6">
                    table row2
                </div>
                <div class="ts-td4">
                    table row3
                </div>
            </div>
        </div>
        <div class="row-fluid table-style">
            <div class="span12 ts-tr">
                <div class="ts-td12">
                    table td12
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <input type="text" value="no-fluid12" class="no-fluid12" />
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <input type="text" value="no-fluid6" class="no-fluid6" />
            </div>
        </div>
    </body>
</html>