<div class="row-fluid">
    <div class="span12">
        <h1><%= $CL.translate('SQLCONNECT::HEADLINE::TABLES') %></h1>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <select name="connection" class="span4">
            <option value="none">- <%= $CL.translate('SQLCONNECT::CHOOSE_CONNECTION') %> -</option>
            <% _.each(connections, function(conData) {%>
            <option value="<%- conData.name  %>"><%- conData.name  %></option>
            <%}) %>
        </select>
    </div>
</div>
<div class="row-fluid table-style">
    <div class="span6 js-sources"></div>
    <div class="span6"></div>
</div>