<?php

namespace Ginger\Model\User;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-21 at 14:41:07.
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User(1);
        $this->object->exchangeArray(array(
            'apiKey' => 'thisisanapikey',
            'secretKey' => 'thisisasecretkey',
            'lastname' => 'mustermann',
            'firstname' => 'max',
            'email' => 'm.mustermann@company.com'
        ));
    }

    /**
     * @covers Ginger\Model\User\User::
     */
    public function testGetId()
    {
        $this->assertEquals(1, $this->object->getId());
    }

    /**
     * @covers Ginger\Model\User\User::getRoleId
     */
    public function testGetRoleId()
    {
        $this->assertEquals('user_1', $this->object->getRoleId());
    }

    /**
     * @covers Ginger\Model\User\User::getApiKey
     */
    public function testGetApiKey()
    {
        $this->assertEquals('thisisanapikey', $this->object->getApiKey());
    }

    /**
     * @covers Ginger\Model\User\User::getSecretKey
     */
    public function testGetSecretKey()
    {
        $this->assertEquals('thisisasecretkey', $this->object->getSecretKey());
    }

    /**
     * @covers Ginger\Model\User\User::getLastname
     */
    public function testGetLastname()
    {
        $this->assertEquals('mustermann', $this->object->getLastname());
    }

    /**
     * @covers Ginger\Model\User\User::getFirstname
     */
    public function testGetFirstname()
    {
        $this->assertEquals('max', $this->object->getFirstname());
    }

    /**
     * @covers Ginger\Model\User\User::getEmail
     */
    public function testGetEmail()
    {
        $this->assertEquals('m.mustermann@company.com', $this->object->getEmail());
    }
}
