<?php
namespace Ginger\Job;

use Cl\Test\PHPUnitTestCase;
use Zend\EventManager\EventManager;
use Ginger\Model\Connector\Connector;
use Ginger\Job\Task\JobTask;

/**
 * Test class for Job.
 * Generated by PHPUnit on 2013-04-05 at 12:31:41.
 */
class JobTest extends PHPUnitTestCase
{

    /**
     * @var Job
     */
    protected $object;

    /**
     *
     * @var \MockObject\Logger
     */
    protected $logger;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Job('testjob');

        $this->logger = new \MockObject\Logger();
        $this->object->setLogger($this->logger);
        $connector = new Connector();
        $connector->setEventManager(new EventManager());
        $this->object->setConcector($connector);
        $this->object->setTranslator(static::getApplication()->getServiceManager()->get('translator'));
    }

    protected function getTask($taskId)
    {
        $task = new JobTask();
        $task->setId($taskId);
        $task->setSource(new \MockObject\Source($taskId, "testsource".$taskId, "/testsource".$taskId, "MockObject"));
        $task->setTarget(new \MockObject\Target($taskId, "testtarget".$taskId, "/testtarget".$taskId, "MockObject"));
        $task->setSourceLoader(new \MockObject\SourceLoader());
        $task->setTargetLoader(new \MockObject\TargetLoader());
        $task->setMapperLoader(new \MockObject\MapperLoader());

        return $task;
    }

    protected function getLogMessages($messages, $type = null) {

        $messageTexts = array();

        foreach ($messages as $message) {
            if (is_null($type) || $type == $message->getType()) {
                $messageTexts[] = $message->getText();
            }
        }

        return $messageTexts;
    }

    /**
     * @covers Ginger\Job\Job::getName
     */
    public function testGetName()
    {
        $this->assertEquals('testjob', $this->object->getName());
    }

    /**
     * @covers Ginger\Job\Job::getConcector
     */
    public function testGetConcector()
    {
        $this->assertInstanceOf('Ginger\Model\Connector\Connector', $this->object->getConcector());
    }

    /**
     * @covers Ginger\Job\Job::getLogger
     */
    public function testGetLogger()
    {
        $this->assertInstanceOf('\MockObject\Logger', $this->object->getLogger());
    }

    /**
     * @covers Ginger\Job\Job::getTasks
     */
    public function testGetTasks()
    {
        $this->assertEquals(0, count($this->object->getTasks()));

        $task = $this->getTask(1);

        $this->object->setTasks(array($task));

        $this->assertEquals(1, count($this->object->getTasks()));
        $this->assertEquals($task, $this->object->getTasks()[0]);
    }

    /**
     * @covers Ginger\Job\Job::addTask
     */
    public function testAddTask()
    {
        $this->assertEquals(0, count($this->object->getTasks()));

        $task = $this->getTask(1);

        $this->object->addTask($task);

        $this->assertEquals(1, count($this->object->getTasks()));
        $this->assertEquals($task, $this->object->getTasks()[0]);
    }

    /**
     * @covers Ginger\Job\Job::getBreakOnFailure
     */
    public function testGetBreakOnFailure()
    {
        $this->assertTrue($this->object->getBreakOnFailure());
    }

    /**
     * @covers Ginger\Job\Job::setBreakOnFailure
     */
    public function testSetBreakOnFailure()
    {
        $this->object->setBreakOnFailure(false);
        $this->assertFalse($this->object->getBreakOnFailure());
    }

    /**
     * @covers Ginger\Job\Job::run
     */
    public function testSuccessfulRun()
    {
        $task = $this->getTask(1);

        $this->object->addTask($task);

        $success = $this->object->run();

        $this->assertTrue($success);

        $checkMessages = array(
            "insert is started",
            "item: item1 is written",
            "item: item2 is written",
            "item: item3 is written",
            "insert is finished",
        );

        $jobRun = $this->logger->getJobRun(0);
        $taskRun = $jobRun->getTaskRuns()[0];

        $this->assertInstanceOf("DateTime", $jobRun->getStartTime());
        $this->assertInstanceOf("DateTime", $jobRun->getEndTime());
        $this->assertTrue($jobRun->getSuccess());
        $this->assertInstanceOf("DateTime", $taskRun->getStartTime());
        $this->assertInstanceOf("DateTime", $taskRun->getEndTime());
        $this->assertTrue($taskRun->getSuccess());
        $this->assertEquals($checkMessages, $this->getLogMessages($taskRun->getMessages()));
    }

    public function testBreakRunWithFailure()
    {
        $failureTask = $this->getTask(2);

        $failureTask->setMapper(new \MockObject\MapperWithError(2, "errormapper", "/errormapper", "MockObject"));

        $successTask = $this->getTask(1);

        $this->object->setTasks(array($failureTask, $successTask));

        $success = $this->object->run();

        $this->assertFalse($success);

        $checkMessages = array(
            'insert is started',
            'item: item1Mapped is written',
            "Can not map item 2.",
            "Der Job wurde abgebrochen, da eine Aufgabe fehlgeschlagen ist.",
        );

        $jobRun = $this->logger->getJobRun(0);

        $messageTexts = array();

        foreach($jobRun->getTaskRuns() as $taskRun) {
            $partTexts = $this->getLogMessages($taskRun->getMessages());
            $messageTexts = array_merge($messageTexts, $partTexts);
        }

        $this->assertEquals($checkMessages, $messageTexts);

        $this->assertInstanceOf("DateTime", $jobRun->getStartTime());
        $this->assertInstanceOf("DateTime", $jobRun->getEndTime());
        $this->assertFalse($jobRun->getSuccess());

        $taskRun1 = $jobRun->getTaskRuns()[0];
        $this->assertInstanceOf("DateTime", $taskRun1->getStartTime());
        $this->assertInstanceOf("DateTime", $taskRun1->getEndTime());
        $this->assertFalse($taskRun1->getSuccess());
        $this->assertEquals(3, $taskRun1->getTotalItemCount());
        $this->assertEquals(1, $taskRun1->getInsertedItemCount());

        
        $this->assertFalse(isset($jobRun->getTaskRuns()[1]));
    }

    public function testNotBreakRunWithFailure()
    {
        $failureTask = $this->getTask(2);

        $failureTask->setMapper(new \MockObject\MapperWithError(2, "errormapper", "/errormapper", "MockObject"));

        $successTask = $this->getTask(1);

        $this->object->setTasks(array($failureTask, $successTask));

        $this->object->setBreakOnFailure(false);

        $success = $this->object->run();

        $this->assertTrue($success);

        $fullMessageStack = array(
            "insert is started",
            "item: item1Mapped is written",
            "Can not map item 2.",
            "insert is started",
            "item: item1 is written",
            "item: item2 is written",
            "item: item3 is written",
            "insert is finished",
        );

        $jobRun = $this->logger->getJobRun(0);

        $messageTexts = array();

        foreach($jobRun->getTaskRuns() as $taskRun) {
            $partTexts = $this->getLogMessages($taskRun->getMessages());
            $messageTexts = array_merge($messageTexts, $partTexts);
        }

        $this->assertEquals($fullMessageStack, $messageTexts);

        $checkErrors = array(
            "Can not map item 2.",
        );

        $messageTexts = array();

        foreach($jobRun->getTaskRuns() as $taskRun) {
            $partTexts = $this->getLogMessages($taskRun->getMessages(), "error");
            $messageTexts = array_merge($messageTexts, $partTexts);
        }

        $this->assertEquals($checkErrors, $messageTexts);

        $this->assertInstanceOf("DateTime", $jobRun->getStartTime());
        $this->assertInstanceOf("DateTime", $jobRun->getEndTime());
        $this->assertTrue($jobRun->getSuccess());

        $taskRun1 = $jobRun->getTaskRuns()[0];
        $this->assertInstanceOf("DateTime", $taskRun1->getStartTime());
        $this->assertInstanceOf("DateTime", $taskRun1->getEndTime());
        $this->assertFalse($taskRun1->getSuccess());
        $this->assertEquals(3, $taskRun1->getTotalItemCount());
        $this->assertEquals(1, $taskRun1->getInsertedItemCount());

        $taskRun2 = $jobRun->getTaskRuns()[1];
        $this->assertInstanceOf("DateTime", $taskRun2->getStartTime());
        $this->assertInstanceOf("DateTime", $taskRun2->getEndTime());
        $this->assertTrue($taskRun2->getSuccess());
        $this->assertEquals(3, $taskRun2->getTotalItemCount());
        $this->assertEquals(3, $taskRun2->getInsertedItemCount());
    }

    public function testHandlingOfFeatures()
    {
        $task = $this->getTask(1);

        $feature = new \MockObject\ValueChangeFeature(1, 'ValueChangeFeature', '/value-change-feature', 'MockObject');
        $feature->setOptions(array(
            'site_to_alter' => 'source',
            'attributes_to_alter' => array(
                'name'
            )
        ));
        $source = new \MockObject\DocumentSource(2, 'DocumentSource', '/document-source', 'MockObject');
        $source->setData(array(
            array(
                'name' => 'item1'
            )
        ));
        $target = new \MockObject\EasyTarget(2, 'EasyTarget', '/easy-target', 'MockObject');
        $task->addFeature($feature);
        $task->setSource($source);
        $task->setTarget($target);

        $this->object->addTask($task);

        $success = $this->object->run();

        $this->assertTrue($success);

        $check = array(
            array(
                'name' => 'item1-changed'
            )
        );

        $this->assertEquals($check, $target->getItems());

        //check that feature is detatched after run
        $task = $this->getTask(1);

        $this->object->setTasks(array($task));

        $success = $this->object->run();

        $this->assertTrue($success);

        $checkMessages = array(
            "insert is started",
            "item: item1 is written",
            "item: item2 is written",
            "item: item3 is written",
            "insert is finished",
        );

        $jobRun = $this->logger->getJobRun(1);
        $taskRun = $jobRun->getTaskRuns()[0];

        $this->assertEquals($checkMessages, $this->getLogMessages($taskRun->getMessages()));
    }
}