<?php
namespace Ginger\Model\Directory;
/**
 * Test class for Inbox.
 * Generated by PHPUnit on 2013-05-27 at 21:15:39.
 */
class InboxTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Inbox
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Inbox::deleteFiles();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        Inbox::deleteFiles();
    }

    /**
     * @covers Ginger\Model\Directory\Inbox::getFirstFileName
     */
    public function testGetFirstFileName()
    {
        file_put_contents('data/inbox/a.json', '');
        file_put_contents('data/inbox/b.xml', '');
        file_put_contents('data/inbox/c.xml', '');

        $filename = Inbox::getFirstFileName('/\.xml$/');

        $this->assertEquals('b.xml', $filename);
    }

    /**
     * @covers Ginger\Model\Directory\Inbox::getFilenames
     */
    public function testGetFilenames()
    {
        file_put_contents('data/inbox/a.json', '');
        file_put_contents('data/inbox/b.xml', '');
        file_put_contents('data/inbox/c.xml', '');

        $filenames = Inbox::getFilenames();

        $this->assertEquals(array('a.json', 'b.xml', 'c.xml'), $filenames);

        $filenames = Inbox::getFilenames('/\.xml$/');

        $this->assertEquals(array('b.xml', 'c.xml'), $filenames);
    }

    /**
     * @covers Ginger\Model\Directory\Inbox::deleteFiles
     */
    public function testDeleteFiles()
    {
        file_put_contents('data/inbox/a.json', '');
        file_put_contents('data/inbox/b.xml', '');
        file_put_contents('data/inbox/c.xml', '');

        Inbox::deleteFiles('/\.xml$/');

        $filenames = Inbox::getFilenames();

        $this->assertEquals(array('a.json'), $filenames);
    }
}

?>
