<?php
namespace Ginger\Model\File\Writer;

use Cl\Filesystem\DirectoryManager;
/**
 * Test class for Json.
 * Generated by PHPUnit on 2013-06-24 at 22:58:21.
 */
class JsonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Json
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Json;
        mkdir('data/tests');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        DirectoryManager::recursiveRemoveDir('data/tests');
    }

    public function testToFile()
    {
        $this->object->toFile('data/tests/test.json', array('one', 'two', 'three'));

        $data = json_decode(file_get_contents('data/tests/test.json'));

        $this->assertEquals(array('one', 'two', 'three'), $data);
    }

    /**
     * @covers Ginger\Model\File\Writer\Json::addToFile
     */
    public function testAddToFile()
    {
        $this->object->toFile('data/tests/test.json', array('one', 'two', 'three'));
        $this->object->addToFile('data/tests/test.json', 'four');

        $data = json_decode(file_get_contents('data/tests/test.json'));

        $this->assertEquals(array('one', 'two', 'three', 'four'), $data);
    }
}

?>
