<?php
namespace Ginger\Model\File\Writer;

use Cl\Filesystem\DirectoryManager;
/**
 * Test class for Xml.
 * Generated by PHPUnit on 2013-06-25 at 21:26:57.
 */
class XmlTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Xml
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Xml;
        mkdir('data/tests');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        DirectoryManager::recursiveRemoveDir('data/tests');
    }

    public function testToFileSingleItemDefaultNaming()
    {
        $data = array(
            'name' => 'Ginger IMS',
            'version' => 0.5,
            'developers' => array(
                array(
                    'name' => 'Alexander Miertsch',
                    'skills' => array(
                        'PHP',
                        'JavaScript',
                        'ZF2',
                        'Backbone',
                        'Codeliner.js'
                    ),
                    'position' => 'architect'
                )
            )
        );

        $this->object->toFile('data/tests/single-item-default-naming.xml', $data);

        $checkXml = file_get_contents('tests/PHPUnit/testdata/xml/single-item-default-naming.xml');
        $writtenXml = file_get_contents('data/tests/single-item-default-naming.xml');

        $this->assertEquals($checkXml, $writtenXml);
    }

    public function testToFileListDefaultNaming()
    {
        $data = array(
            array(
                'name' => 'Ginger IMS',
                'version' => 0.5,
                'developers' => array(
                    array(
                        'name' => 'Alexander Miertsch',
                        'skills' => array(
                            'PHP',
                            'JavaScript',
                            'ZF2',
                            'Backbone',
                            'Codeliner.js'
                        ),
                        'position' => 'architect'
                    )
                )
            ),
            array(
                'name' => 'Codeliner.js',
                'version' => '2.0',
                'developers' => array(
                    array(
                        'name' => 'Alexander Miertsch',
                        'skills' => array(
                            'PHP',
                            'JavaScript',
                            'ZF2',
                            'Backbone',
                            'Codeliner.js'
                        ),
                        'position' => 'architect'
                    )
                )
            ),
        );

        $this->object->toFile('data/tests/list-default-naming.xml', $data);

        $checkXml = file_get_contents('tests/PHPUnit/testdata/xml/list-default-naming.xml');
        $writtenXml = file_get_contents('data/tests/list-default-naming.xml');

        $this->assertEquals($checkXml, $writtenXml);
    }

    public function testToFileSingleItemDataPaths()
    {
        $data = array(
            'name' => 'Ginger IMS',
            'version' => 0.5,
            'developers' => array(
                array(
                    'name' => 'Alexander Miertsch',
                    'skills' => array(
                        'PHP',
                        'JavaScript',
                        'ZF2',
                        'Backbone',
                        'Codeliner.js'
                    ),
                    'position' => 'architect'
                )
            )
        );

        $this->object->setItemName('project');
        $this->object->setListName('projects');
        $this->object->setDataPaths(array(
            'project',
            'project::name',
            'project::version',
            'project::developers',
            'project::developers::[developer]',
            'project::developers::[developer]::name',
            'project::developers::[developer]::skills',
            'project::developers::[developer]::skills::[skill]',
            'project::developers::[developer]::position'
        ));


        $this->object->toFile('data/tests/single-item-data-paths.xml', $data);

        $checkXml = file_get_contents('tests/PHPUnit/testdata/xml/single-item-data-paths.xml');
        $writtenXml = file_get_contents('data/tests/single-item-data-paths.xml');

        $this->assertEquals($checkXml, $writtenXml);
    }

    public function testToFileListDataPaths()
    {
        $data = array(
            array(
                'name' => 'Ginger IMS',
                'version' => 0.5,
                'developers' => array(
                    array(
                        'name' => 'Alexander Miertsch',
                        'skills' => array(
                            'PHP',
                            'JavaScript',
                            'ZF2',
                            'Backbone',
                            'Codeliner.js'
                        ),
                        'position' => 'architect'
                    ),
                    array(
                        'name' => 'D.F.',
                        'skills' => array(
                            'CSS',
                            'Design',
                            'CS Suite',
                        ),
                        'position' => 'grafic design'
                    )
                )
            ),
            array(
                'name' => 'Codeliner.js',
                'version' => '2.0',
                'developers' => array(
                    array(
                        'name' => 'Alexander Miertsch',
                        'skills' => array(
                            'PHP',
                            'JavaScript',
                            'ZF2',
                            'Backbone',
                            'Codeliner.js'
                        ),
                        'position' => 'architect'
                    )
                )
            ),
        );

        $this->object->setItemName('project');
        $this->object->setListName('projects');
        $this->object->setDataPaths(array(
            'projects',
            'projects::[project]',
            'projects::[project]::name',
            'projects::[project]::version',
            'projects::[project]::developers',
            'projects::[project]::developers::[developer]',
            'projects::[project]::developers::[developer]::name',
            'projects::[project]::developers::[developer]::skills',
            'projects::[project]::developers::[developer]::skills::[skill]',
            'projects::[project]::developers::[developer]::position'
        ));


        $this->object->toFile('data/tests/list-data-paths.xml', $data);

        $checkXml = file_get_contents('tests/PHPUnit/testdata/xml/list-data-paths.xml');
        $writtenXml = file_get_contents('data/tests/list-data-paths.xml');

        $this->assertEquals($checkXml, $writtenXml);
    }

    public function testToFileSingleItemDefaultDataPaths()
    {
        $data = array(
            'name' => 'Ginger IMS',
            'version' => 0.5,
            'developers' => array(
                array(
                    'name' => 'Alexander Miertsch',
                    'skills' => array(
                        'PHP',
                        'JavaScript',
                        'ZF2',
                        'Backbone',
                        'Codeliner.js'
                    ),
                    'position' => 'architect'
                )
            )
        );

        $this->object->setItemName('project');
        $this->object->setListName('projects');
        $this->object->setDataPaths(array(
            'project',
            'project::name',
            'project::version',
            'project::developers',
            'project::developers::[]',
            'project::developers::[]::name',
            'project::developers::[]::skills',
            'project::developers::[]::skills::[]',
            'project::developers::[]::position'
        ));


        $this->object->toFile('data/tests/single-item-default-data-paths.xml', $data);

        $checkXml = file_get_contents('tests/PHPUnit/testdata/xml/single-item-default-data-paths.xml');
        $writtenXml = file_get_contents('data/tests/single-item-default-data-paths.xml');

        $this->assertEquals($checkXml, $writtenXml);
    }

    public function testToFileListDefaultDataPaths()
    {
        $data = array(
            array(
                'name' => 'Ginger IMS',
                'version' => 0.5,
                'developers' => array(
                    array(
                        'name' => 'Alexander Miertsch',
                        'skills' => array(
                            'PHP',
                            'JavaScript',
                            'ZF2',
                            'Backbone',
                            'Codeliner.js'
                        ),
                        'position' => 'architect'
                    ),
                    array(
                        'name' => 'D.F.',
                        'skills' => array(
                            'CSS',
                            'Design',
                            'CS Suite',
                        ),
                        'position' => 'grafic design'
                    )
                )
            ),
            array(
                'name' => 'Codeliner.js',
                'version' => '2.0',
                'developers' => array(
                    array(
                        'name' => 'Alexander Miertsch',
                        'skills' => array(
                            'PHP',
                            'JavaScript',
                            'ZF2',
                            'Backbone',
                            'Codeliner.js'
                        ),
                        'position' => 'architect'
                    )
                )
            ),
        );

        $this->object->setItemName('project');
        $this->object->setListName('projects');
        $this->object->setDataPaths(array(
            'projects',
            'projects::[]',
            'projects::[]::name',
            'projects::[]::version',
            'projects::[]::developers',
            'projects::[]::developers::[]',
            'projects::[]::developers::[]::name',
            'projects::[]::developers::[]::skills',
            'projects::[]::developers::[]::skills::[]',
            'projects::[]::developers::[]::position'
        ));


        $this->object->toFile('data/tests/list-default-data-paths.xml', $data);

        $checkXml = file_get_contents('tests/PHPUnit/testdata/xml/list-default-data-paths.xml');
        $writtenXml = file_get_contents('data/tests/list-default-data-paths.xml');

        $this->assertEquals($checkXml, $writtenXml);
    }
}

?>
