<div class="row-fluid">
    <div class="span12">
        <h1>SqlConnect</h1>
    </div>
</div>
<div class="row-fluid">
    <div class="span6 well well-block">
        <p>
            <%= $CL.translate('SQLCONNECT::SOURCES::INFO') %>
        </p>
        <a href="#<% print(helpers.uri('sqlconnect_sources')) %>" class="btn"><%= $CL.translate('SQLCONNECT::BUTTON::MANAGE_SOURCES')%></a>
    </div>
    <div class="span6 well well-block">
        <p>
            <%= $CL.translate('SQLCONNECT::TARGETS::INFO') %>
        </p>
        <a href="#<% print(helpers.uri('sqlconnect_targets')) %>" class="btn sqlconnect-targets"><%= $CL.translate('SQLCONNECT::BUTTON::MANAGE_TARGETS')%></a>
    </div>

</div>
<div class="row-fluid">
    <div class="span6 well well-block">
        <p>
            <%= $CL.translate('SQLCONNECT::CONNECTION::INFO') %>
        </p>
        <a href="#<% print(helpers.uri('sqlconnect_configuration')) %>" class="btn sqlconnect-configuration"><%= $CL.translate('SQLCONNECT::BUTTON::MANAGE_CONNECTIONS')%></a>
    </div>
    <div class="span6"></div>
</div>

