<?php

namespace Ginger\Repository;

use Cl\Test\DoctrineTestCase;
use Ginger\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-26 at 15:18:52.
 */
class PermissionRepositoryTest extends DoctrineTestCase
{

    /**
     * @var PermissionRepository
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->createEntitySchema('Ginger\Entity\User');
        $this->createEntitySchema('Ginger\Entity\Job');
        $this->createEntitySchema('Ginger\Entity\Permission');
        $this->object = $this->getTestEntityManager()->getRepository('Ginger\Entity\Permission');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ginger\Repository\PermissionRepository::loadPermissions
     * @todo   Implement testLoadPermissions().
     */
    public function testLoadPermissions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ginger\Repository\PermissionRepository::savePermissions
     * @todo   Implement testSavePermissions().
     */
    public function testSavePermissions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ginger\Repository\PermissionRepository::deletePermissions
     * @todo   Implement testDeletePermissions().
     */
    public function testDeletePermissions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
