<div class="row-fluid">
    <div class="span12">
        <h2><%= $CL.translate('HEADLINE::JOBS::ADD') %></h2>
    </div>
</div>
<div class="row-fluid">
    <div class="span12  row-label-element desktop-span7">
        <% print(Cl.Form.View.InputText.print(form.getElement('name'), form.getErrors())); %>
    </div>
    <div class="desktop-span5 visible-desktop"></div>
</div>
<div class="row-fluid">
    <div class="span12 row-textarea desktop-span7">
        <% print(Cl.Form.View.Textarea.print(form.getElement('description'), form.getErrors())); %>
    </div>
    <div class="desktop-span5 visible-desktop"></div>
</div>
<div class="row-fluid">
    <div class="span12">
        <input type="submit" name="save" value="<%= $CL.translate('FORM::BUTTON::SAVE') %>"
    </div>
</div>