<div class="row-fluid">
    <div class="span12">
        <h1><%- name %></h1>
    </div>
</div>
<div class="row-fluid">
    <div class="span6 well well-large">
        <fieldset>
            <legend><%= $CL.translate('GENERAL::DESCRIPTION') %></legend>
            <div class="row-fluid">
                <div class="span12">
                    <textarea name="description" class="span12"><%= description %></textarea>
                </div>
            </div>
        </fieldset>
    </div>
    <div class="span6 well well-large">
        <fieldset>
            <legend><%= $CL.translate('JOBS::HEADLINE::ERROR_HANDLING') %></legend>
            <div class="row-fluid">
                <div class="span6">
                    <label for="break_on_failure"><input type="radio" name="break_on_failure" value="1"
                                                       <% if (break_on_failure) {print('checked="checked"')} %>
                                                       />&nbsp;<span class="label"><%= $CL.translate('JOBS::LABEL::BREAK_ON_FAILURE') %></span></label>
                </div>
                <div class="span6">
                    <label for="break_on_failure"><input type="radio" name="break_on_failure" value="0"
                                                       <% if (!break_on_failure) {print('checked="checked"')} %>
                                                       />&nbsp;<span class="label"><%= $CL.translate('JOBS::LABEL::NOT_BREAK_ON_FAILURE') %></span></label>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="well well-large">
    <div class="row-fluid">
        <div class="span6">
            <h2><%= $CL.translate('HEADLINE::JOBS::CONFIGURATIONS') %></h2>
        </div>
        <div class="span6">
            <a href="#<% print(helpers.uri('jobs_configuration_add', {jobname : obj.name})) %>" class="btn pull-right js-add-configuration"><%= $CL.translate('JOBS::BUTTON::CONFIGURATION::ADD') %>&nbsp;<i class="icon-plus"></i></a>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="table-style">
                <div class="ts-tr">
                    <div class="ts-th ts-td5">
                        <%= $CL.translate('GENERAL::SOURCE') %>
                    </div>
                    <div class="ts-th ts-td5">
                        <%= $CL.translate('GENERAL::TARGET') %>
                    </div>
                    <div class="ts-th ts-td2">&nbsp;</div>
                </div>
                <% _.each(configurations, function(configuration){%>
                <div class="ts-tr js-configuration">
                    <div class="ts-td5"><%= helpers.wrapVisibleSpans(configuration.source.module + '::' + configuration.source.name, '::') %></div>
                    <div class="ts-td5"><%= helpers.wrapVisibleSpans(configuration.target.module + '::' + configuration.target.name, '::') %></div>
                    <div class="ts-td2">
                        <% print($CL._template('application_edit_remove')({id : configuration.id})) %>
                    </div>
                </div>
                <%}) %>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span6 well well-large">
        <fieldset>
            <legend><%= $CL.translate('GENERAL::PERMISSIONS') %></legend>
        </fieldset>
    </div>
    <div class="span6 well well-large">
        <fieldset>
            <legend><%= $CL.translate('GENERAL::TIME_SCHEDULE') %></legend>
        </fieldset>
    </div>
</div>
<div class="row-fluid">
    <div class="span12 form-actions">
        <button class="btn btn-primary js-save-btn"><%= $CL.translate('BUTTON::SAVE') %></button>
            <button class="btn close js-remove-job-btn"><%= $CL.translate('JOBS::BUTTON::DELETE') %></button>
    </div>
</div>