<?php
namespace Ginger\Model\File\Reader;

use Cl\Filesystem\DirectoryManager;
/**
 * Test class for Json.
 * Generated by PHPUnit on 2013-06-24 at 22:19:51.
 */
class JsonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Json
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Json;
        mkdir('data/tests');
        file_put_contents('data/tests/test.json', json_encode(\MockObject\FileDataStub::getData()));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        DirectoryManager::recursiveRemoveDir('data/tests');
    }

    /**
     * @covers Ginger\Model\File\Reader\Json::fromFile
     */
    public function testFromFile()
    {
        $data = $this->object->fromFile('data/tests/test.json');
        $this->assertEquals(\MockObject\FileDataStub::getData(), $data);
    }

}
?>
