<?php
namespace Ginger\Service\Auth;

use Zend\Authentication\Result;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-03 at 10:17:07.
 */
class ApiKeyAdapterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ApiKeyAdapter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $userLoader = new \MockObject\UserLoaderMock();
        $userLoader->setUsersData(array(
            0 => array(
                'id' => 0,
                'apiKey' => '12345key',
                'secretKey' => '6789secret',
                'lastname' => 'mustermann',
                'firstname' => 'max',
                'email' => 'm.mustermann@company.com',
                'isAdmin' => false,
            )
        ));
        
        $this->object = new ApiKeyAdapter($userLoader);
        $this->object->setRequestUri('/test/request/uri');
    }

    /**
     * @covers Ginger\Service\Auth\ApiKeyAdapter::authenticate
     */
    public function testAuthenticate()
    {
        $requestHash = hash_hmac('sha1', '/test/request/uri', '6789secret');
        
        $this->object->setRequestHash($requestHash);
        $this->object->setApiKey('12345key');
        
        $result = $this->object->authenticate();
        
        $this->assertTrue($result->isValid());
        $this->assertEquals('mustermann', $result->getIdentity()['lastname']);
    }

    /**
     * @covers Ginger\Service\Auth\ApiKeyAdapter::authenticate
     */
    public function testIdentityNotFound()
    {
        $requestHash = hash_hmac('sha1', '/test/request/uri', '6789secret');
        
        $this->object->setRequestHash($requestHash);
        $this->object->setApiKey('555key');
        
        $result = $this->object->authenticate();
        
        $this->assertFalse($result->isValid());
        $this->assertEquals(Result::FAILURE_IDENTITY_NOT_FOUND, $result->getCode());
    }
    
    /**
     * @covers Ginger\Service\Auth\ApiKeyAdapter::authenticate
     */
    public function testInvalidCredentials()
    {
        $requestHash = hash_hmac('sha1', '/test/request/uri', '777secret');
        
        $this->object->setRequestHash($requestHash);
        $this->object->setApiKey('12345key');
        
        $result = $this->object->authenticate();
        
        $this->assertFalse($result->isValid());
        $this->assertEquals(Result::FAILURE_CREDENTIAL_INVALID, $result->getCode());
    }
}
